/* tslint:disable */
/* eslint-disable */
/**
 * PERSCOM Personnel Management System API
 * The PERSCOM API describes how to interact and manipulate your PERSCOM data available at https://perscom.io. The API provides a powerful interface to allow for third-party collaboration and integration with your PERSCOM Dashboard.
 *
 * The version of the OpenAPI document: v2
 * Contact: support@deschutesdesigngroup.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Award
 */
export interface Award {
    /**
     * 
     * @type {string}
     * @memberof Award
     */
    name: string;
    /**
     * Supports HTML.
     * @type {string}
     * @memberof Award
     */
    description?: string | null;
    /**
     * Will be auto-calculated if nothing is provided.
     * @type {number}
     * @memberof Award
     */
    order?: number;
}

/**
 * Check if a given object implements the Award interface.
 */
export function instanceOfAward(value: object): value is Award {
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function AwardFromJSON(json: any): Award {
    return AwardFromJSONTyped(json, false);
}

export function AwardFromJSONTyped(json: any, ignoreDiscriminator: boolean): Award {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'description': json['description'] == null ? undefined : json['description'],
        'order': json['order'] == null ? undefined : json['order'],
    };
}

export function AwardToJSON(json: any): Award {
    return AwardToJSONTyped(json, false);
}

export function AwardToJSONTyped(value?: Award | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'description': value['description'],
        'order': value['order'],
    };
}

