/* tslint:disable */
/* eslint-disable */
/**
 * PERSCOM Personnel Management System API
 * The PERSCOM API describes how to interact and manipulate your PERSCOM data available at https://perscom.io. The API provides a powerful interface to allow for third-party collaboration and integration with your PERSCOM Dashboard.
 *
 * The version of the OpenAPI document: v2
 * Contact: support@deschutesdesigngroup.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Field
 */
export interface Field {
    /**
     * 
     * @type {string}
     * @memberof Field
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof Field
     */
    key?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Field
     */
    type?: string;
    /**
     * 
     * @type {string}
     * @memberof Field
     */
    cast?: string | null;
    /**
     * Supports HTML.
     * @type {string}
     * @memberof Field
     */
    description?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Field
     */
    placeholder?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Field
     */
    _default?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Field
     */
    help?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof Field
     */
    required?: boolean;
    /**
     * 
     * @type {string}
     * @memberof Field
     */
    rules?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof Field
     */
    readonly?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof Field
     */
    hidden?: boolean;
    /**
     * 
     * @type {Array<object>}
     * @memberof Field
     */
    options?: Array<object>;
    /**
     * 
     * @type {string}
     * @memberof Field
     */
    optionsType?: FieldOptionsTypeEnum;
    /**
     * If the options type is a model, this is the resource that should populate the options field.
     * @type {string}
     * @memberof Field
     */
    optionsModel?: string;
}


/**
 * @export
 */
export const FieldOptionsTypeEnum = {
    Array: 'array',
    Model: 'model'
} as const;
export type FieldOptionsTypeEnum = typeof FieldOptionsTypeEnum[keyof typeof FieldOptionsTypeEnum];


/**
 * Check if a given object implements the Field interface.
 */
export function instanceOfField(value: object): value is Field {
    return true;
}

export function FieldFromJSON(json: any): Field {
    return FieldFromJSONTyped(json, false);
}

export function FieldFromJSONTyped(json: any, ignoreDiscriminator: boolean): Field {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
        'key': json['key'] == null ? undefined : json['key'],
        'type': json['type'] == null ? undefined : json['type'],
        'cast': json['cast'] == null ? undefined : json['cast'],
        'description': json['description'] == null ? undefined : json['description'],
        'placeholder': json['placeholder'] == null ? undefined : json['placeholder'],
        '_default': json['default'] == null ? undefined : json['default'],
        'help': json['help'] == null ? undefined : json['help'],
        'required': json['required'] == null ? undefined : json['required'],
        'rules': json['rules'] == null ? undefined : json['rules'],
        'readonly': json['readonly'] == null ? undefined : json['readonly'],
        'hidden': json['hidden'] == null ? undefined : json['hidden'],
        'options': json['options'] == null ? undefined : json['options'],
        'optionsType': json['options_type'] == null ? undefined : json['options_type'],
        'optionsModel': json['options_model'] == null ? undefined : json['options_model'],
    };
}

export function FieldToJSON(json: any): Field {
    return FieldToJSONTyped(json, false);
}

export function FieldToJSONTyped(value?: Field | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'key': value['key'],
        'type': value['type'],
        'cast': value['cast'],
        'description': value['description'],
        'placeholder': value['placeholder'],
        'default': value['_default'],
        'help': value['help'],
        'required': value['required'],
        'rules': value['rules'],
        'readonly': value['readonly'],
        'hidden': value['hidden'],
        'options': value['options'],
        'options_type': value['optionsType'],
        'options_model': value['optionsModel'],
    };
}

