/* tslint:disable */
/* eslint-disable */
/**
 * PERSCOM Personnel Management System API
 * The PERSCOM API describes how to interact and manipulate your PERSCOM data available at https://perscom.io. The API provides a powerful interface to allow for third-party collaboration and integration with your PERSCOM Dashboard.
 *
 * The version of the OpenAPI document: v2
 * Contact: support@deschutesdesigngroup.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ImageResource
 */
export interface ImageResource {
    /**
     * 
     * @type {string}
     * @memberof ImageResource
     */
    name: string;
    /**
     * Supports HTML.
     * @type {string}
     * @memberof ImageResource
     */
    description?: string | null;
    /**
     * The file to be uploaded.
     * @type {Blob}
     * @memberof ImageResource
     */
    image: Blob;
    /**
     * 
     * @type {string}
     * @memberof ImageResource
     */
    readonly filename?: string;
    /**
     * 
     * @type {string}
     * @memberof ImageResource
     */
    readonly path?: string;
    /**
     * 
     * @type {string}
     * @memberof ImageResource
     */
    readonly imageUrl?: string;
    /**
     * 
     * @type {string}
     * @memberof ImageResource
     */
    label?: string;
    /**
     * The date the resource was created. Stored in UTC.
     * @type {Date}
     * @memberof ImageResource
     */
    createdAt?: Date;
    /**
     * The date the resource was updated. Stored in UTC.
     * @type {Date}
     * @memberof ImageResource
     */
    updatedAt?: Date;
    /**
     * 
     * @type {number}
     * @memberof ImageResource
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof ImageResource
     */
    modelType?: string | null;
    /**
     * 
     * @type {number}
     * @memberof ImageResource
     */
    modelId?: number | null;
}

/**
 * Check if a given object implements the ImageResource interface.
 */
export function instanceOfImageResource(value: object): value is ImageResource {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('image' in value) || value['image'] === undefined) return false;
    return true;
}

export function ImageResourceFromJSON(json: any): ImageResource {
    return ImageResourceFromJSONTyped(json, false);
}

export function ImageResourceFromJSONTyped(json: any, ignoreDiscriminator: boolean): ImageResource {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'description': json['description'] == null ? undefined : json['description'],
        'image': json['image'],
        'filename': json['filename'] == null ? undefined : json['filename'],
        'path': json['path'] == null ? undefined : json['path'],
        'imageUrl': json['image_url'] == null ? undefined : json['image_url'],
        'label': json['label'] == null ? undefined : json['label'],
        'createdAt': json['created_at'] == null ? undefined : (new Date(json['created_at'])),
        'updatedAt': json['updated_at'] == null ? undefined : (new Date(json['updated_at'])),
        'id': json['id'] == null ? undefined : json['id'],
        'modelType': json['model_type'] == null ? undefined : json['model_type'],
        'modelId': json['model_id'] == null ? undefined : json['model_id'],
    };
}

export function ImageResourceToJSON(json: any): ImageResource {
    return ImageResourceToJSONTyped(json, false);
}

export function ImageResourceToJSONTyped(value?: Omit<ImageResource, 'filename'|'path'|'image_url'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'description': value['description'],
        'image': value['image'],
        'label': value['label'],
        'created_at': value['createdAt'] == null ? undefined : ((value['createdAt']).toISOString()),
        'updated_at': value['updatedAt'] == null ? undefined : ((value['updatedAt']).toISOString()),
        'id': value['id'],
        'model_type': value['modelType'],
        'model_id': value['modelId'],
    };
}

