/* tslint:disable */
/* eslint-disable */
/**
 * PERSCOM Personnel Management System API
 * The PERSCOM API describes how to interact and manipulate your PERSCOM data available at https://perscom.io. The API provides a powerful interface to allow for third-party collaboration and integration with your PERSCOM Dashboard.
 *
 * The version of the OpenAPI document: v2
 * Contact: support@deschutesdesigngroup.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Model401Error
 */
export interface Model401Error {
    /**
     * 
     * @type {string}
     * @memberof Model401Error
     */
    message?: string;
    /**
     * 
     * @type {string}
     * @memberof Model401Error
     */
    type?: string;
}

/**
 * Check if a given object implements the Model401Error interface.
 */
export function instanceOfModel401Error(value: object): value is Model401Error {
    return true;
}

export function Model401ErrorFromJSON(json: any): Model401Error {
    return Model401ErrorFromJSONTyped(json, false);
}

export function Model401ErrorFromJSONTyped(json: any, ignoreDiscriminator: boolean): Model401Error {
    if (json == null) {
        return json;
    }
    return {
        
        'message': json['message'] == null ? undefined : json['message'],
        'type': json['type'] == null ? undefined : json['type'],
    };
}

export function Model401ErrorToJSON(json: any): Model401Error {
    return Model401ErrorToJSONTyped(json, false);
}

export function Model401ErrorToJSONTyped(value?: Model401Error | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'message': value['message'],
        'type': value['type'],
    };
}

