/* tslint:disable */
/* eslint-disable */
/**
 * PERSCOM Personnel Management System API
 * The PERSCOM API describes how to interact and manipulate your PERSCOM data available at https://perscom.io. The API provides a powerful interface to allow for third-party collaboration and integration with your PERSCOM Dashboard.
 *
 * The version of the OpenAPI document: v2
 * Contact: support@deschutesdesigngroup.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface QualificationRecord
 */
export interface QualificationRecord {
    /**
     * 
     * @type {number}
     * @memberof QualificationRecord
     */
    userId: number;
    /**
     * 
     * @type {number}
     * @memberof QualificationRecord
     */
    qualificationId: number;
    /**
     * 
     * @type {number}
     * @memberof QualificationRecord
     */
    documentId?: number | null;
    /**
     * 
     * @type {number}
     * @memberof QualificationRecord
     */
    authorId?: number | null;
    /**
     * Supports HTML.
     * @type {string}
     * @memberof QualificationRecord
     */
    text?: string | null;
}

/**
 * Check if a given object implements the QualificationRecord interface.
 */
export function instanceOfQualificationRecord(value: object): value is QualificationRecord {
    if (!('userId' in value) || value['userId'] === undefined) return false;
    if (!('qualificationId' in value) || value['qualificationId'] === undefined) return false;
    return true;
}

export function QualificationRecordFromJSON(json: any): QualificationRecord {
    return QualificationRecordFromJSONTyped(json, false);
}

export function QualificationRecordFromJSONTyped(json: any, ignoreDiscriminator: boolean): QualificationRecord {
    if (json == null) {
        return json;
    }
    return {
        
        'userId': json['user_id'],
        'qualificationId': json['qualification_id'],
        'documentId': json['document_id'] == null ? undefined : json['document_id'],
        'authorId': json['author_id'] == null ? undefined : json['author_id'],
        'text': json['text'] == null ? undefined : json['text'],
    };
}

export function QualificationRecordToJSON(json: any): QualificationRecord {
    return QualificationRecordToJSONTyped(json, false);
}

export function QualificationRecordToJSONTyped(value?: QualificationRecord | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'user_id': value['userId'],
        'qualification_id': value['qualificationId'],
        'document_id': value['documentId'],
        'author_id': value['authorId'],
        'text': value['text'],
    };
}

