/* tslint:disable */
/* eslint-disable */
/**
 * PERSCOM Personnel Management System API
 * The PERSCOM API describes how to interact and manipulate your PERSCOM data available at https://perscom.io. The API provides a powerful interface to allow for third-party collaboration and integration with your PERSCOM Dashboard.
 *
 * The version of the OpenAPI document: v2
 * Contact: support@deschutesdesigngroup.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RankResource
 */
export interface RankResource {
    /**
     * 
     * @type {string}
     * @memberof RankResource
     */
    name: string;
    /**
     * Supports HTML.
     * @type {string}
     * @memberof RankResource
     */
    description?: string | null;
    /**
     * 
     * @type {string}
     * @memberof RankResource
     */
    abbreviation?: string | null;
    /**
     * 
     * @type {string}
     * @memberof RankResource
     */
    paygrade?: string | null;
    /**
     * Will be auto-calculated if nothing is provided.
     * @type {number}
     * @memberof RankResource
     */
    order?: number;
    /**
     * 
     * @type {string}
     * @memberof RankResource
     */
    label?: string;
    /**
     * The date the resource was created. Stored in UTC.
     * @type {Date}
     * @memberof RankResource
     */
    createdAt?: Date;
    /**
     * The date the resource was updated. Stored in UTC.
     * @type {Date}
     * @memberof RankResource
     */
    updatedAt?: Date;
    /**
     * 
     * @type {number}
     * @memberof RankResource
     */
    id?: number;
}

/**
 * Check if a given object implements the RankResource interface.
 */
export function instanceOfRankResource(value: object): value is RankResource {
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function RankResourceFromJSON(json: any): RankResource {
    return RankResourceFromJSONTyped(json, false);
}

export function RankResourceFromJSONTyped(json: any, ignoreDiscriminator: boolean): RankResource {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'description': json['description'] == null ? undefined : json['description'],
        'abbreviation': json['abbreviation'] == null ? undefined : json['abbreviation'],
        'paygrade': json['paygrade'] == null ? undefined : json['paygrade'],
        'order': json['order'] == null ? undefined : json['order'],
        'label': json['label'] == null ? undefined : json['label'],
        'createdAt': json['created_at'] == null ? undefined : (new Date(json['created_at'])),
        'updatedAt': json['updated_at'] == null ? undefined : (new Date(json['updated_at'])),
        'id': json['id'] == null ? undefined : json['id'],
    };
}

export function RankResourceToJSON(json: any): RankResource {
    return RankResourceToJSONTyped(json, false);
}

export function RankResourceToJSONTyped(value?: RankResource | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'description': value['description'],
        'abbreviation': value['abbreviation'],
        'paygrade': value['paygrade'],
        'order': value['order'],
        'label': value['label'],
        'created_at': value['createdAt'] == null ? undefined : ((value['createdAt']).toISOString()),
        'updated_at': value['updatedAt'] == null ? undefined : ((value['updatedAt']).toISOString()),
        'id': value['id'],
    };
}

