/* tslint:disable */
/* eslint-disable */
/**
 * PERSCOM Personnel Management System API
 * The PERSCOM API describes how to interact and manipulate your PERSCOM data available at https://perscom.io. The API provides a powerful interface to allow for third-party collaboration and integration with your PERSCOM Dashboard.
 *
 * The version of the OpenAPI document: v2
 * Contact: support@deschutesdesigngroup.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ResourceMeta
 */
export interface ResourceMeta {
    /**
     * 
     * @type {number}
     * @memberof ResourceMeta
     */
    currentPage?: number;
    /**
     * 
     * @type {number}
     * @memberof ResourceMeta
     */
    from?: number;
    /**
     * 
     * @type {number}
     * @memberof ResourceMeta
     */
    lastPage?: number;
    /**
     * 
     * @type {string}
     * @memberof ResourceMeta
     */
    path?: string;
    /**
     * 
     * @type {number}
     * @memberof ResourceMeta
     */
    perPage?: number;
    /**
     * 
     * @type {number}
     * @memberof ResourceMeta
     */
    to?: number;
    /**
     * 
     * @type {number}
     * @memberof ResourceMeta
     */
    total?: number;
}

/**
 * Check if a given object implements the ResourceMeta interface.
 */
export function instanceOfResourceMeta(value: object): value is ResourceMeta {
    return true;
}

export function ResourceMetaFromJSON(json: any): ResourceMeta {
    return ResourceMetaFromJSONTyped(json, false);
}

export function ResourceMetaFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResourceMeta {
    if (json == null) {
        return json;
    }
    return {
        
        'currentPage': json['current_page'] == null ? undefined : json['current_page'],
        'from': json['from'] == null ? undefined : json['from'],
        'lastPage': json['last_page'] == null ? undefined : json['last_page'],
        'path': json['path'] == null ? undefined : json['path'],
        'perPage': json['per_page'] == null ? undefined : json['per_page'],
        'to': json['to'] == null ? undefined : json['to'],
        'total': json['total'] == null ? undefined : json['total'],
    };
}

export function ResourceMetaToJSON(json: any): ResourceMeta {
    return ResourceMetaToJSONTyped(json, false);
}

export function ResourceMetaToJSONTyped(value?: ResourceMeta | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'current_page': value['currentPage'],
        'from': value['from'],
        'last_page': value['lastPage'],
        'path': value['path'],
        'per_page': value['perPage'],
        'to': value['to'],
        'total': value['total'],
    };
}

