/* tslint:disable */
/* eslint-disable */
/**
 * PERSCOM Personnel Management System API
 * The PERSCOM API describes how to interact and manipulate your PERSCOM data available at https://perscom.io. The API provides a powerful interface to allow for third-party collaboration and integration with your PERSCOM Dashboard.
 *
 * The version of the OpenAPI document: v2
 * Contact: support@deschutesdesigngroup.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SettingsPayload
 */
export interface SettingsPayload {
}

/**
 * Check if a given object implements the SettingsPayload interface.
 */
export function instanceOfSettingsPayload(value: object): value is SettingsPayload {
    return true;
}

export function SettingsPayloadFromJSON(json: any): SettingsPayload {
    return SettingsPayloadFromJSONTyped(json, false);
}

export function SettingsPayloadFromJSONTyped(json: any, ignoreDiscriminator: boolean): SettingsPayload {
    return json;
}

export function SettingsPayloadToJSON(json: any): SettingsPayload {
    return SettingsPayloadToJSONTyped(json, false);
}

export function SettingsPayloadToJSONTyped(value?: SettingsPayload | null, ignoreDiscriminator: boolean = false): any {
    return value;
}

