/* tslint:disable */
/* eslint-disable */
/**
 * PERSCOM Personnel Management System API
 * The PERSCOM API describes how to interact and manipulate your PERSCOM data available at https://perscom.io. The API provides a powerful interface to allow for third-party collaboration and integration with your PERSCOM Dashboard.
 *
 * The version of the OpenAPI document: v2
 * Contact: support@deschutesdesigngroup.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Specialty
 */
export interface Specialty {
    /**
     * 
     * @type {string}
     * @memberof Specialty
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof Specialty
     */
    abbreviation?: string | null;
    /**
     * Supports HTML.
     * @type {string}
     * @memberof Specialty
     */
    description?: string | null;
    /**
     * Will be auto-calculated if nothing is provided.
     * @type {number}
     * @memberof Specialty
     */
    order?: number;
}

/**
 * Check if a given object implements the Specialty interface.
 */
export function instanceOfSpecialty(value: object): value is Specialty {
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function SpecialtyFromJSON(json: any): Specialty {
    return SpecialtyFromJSONTyped(json, false);
}

export function SpecialtyFromJSONTyped(json: any, ignoreDiscriminator: boolean): Specialty {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'abbreviation': json['abbreviation'] == null ? undefined : json['abbreviation'],
        'description': json['description'] == null ? undefined : json['description'],
        'order': json['order'] == null ? undefined : json['order'],
    };
}

export function SpecialtyToJSON(json: any): Specialty {
    return SpecialtyToJSONTyped(json, false);
}

export function SpecialtyToJSONTyped(value?: Specialty | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'abbreviation': value['abbreviation'],
        'description': value['description'],
        'order': value['order'],
    };
}

