/* tslint:disable */
/* eslint-disable */
/**
 * PERSCOM Personnel Management System API
 * The PERSCOM API describes how to interact and manipulate your PERSCOM data available at https://perscom.io. The API provides a powerful interface to allow for third-party collaboration and integration with your PERSCOM Dashboard.
 *
 * The version of the OpenAPI document: v2
 * Contact: support@deschutesdesigngroup.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TaskResource
 */
export interface TaskResource {
    /**
     * 
     * @type {string}
     * @memberof TaskResource
     */
    title: string;
    /**
     * Supports HTML.
     * @type {string}
     * @memberof TaskResource
     */
    description?: string | null;
    /**
     * Supports HTML.
     * @type {string}
     * @memberof TaskResource
     */
    instructions?: string | null;
    /**
     * 
     * @type {number}
     * @memberof TaskResource
     */
    formId?: number | null;
    /**
     * 
     * @type {string}
     * @memberof TaskResource
     */
    label?: string;
    /**
     * The date the resource was created. Stored in UTC.
     * @type {Date}
     * @memberof TaskResource
     */
    createdAt?: Date;
    /**
     * The date the resource was updated. Stored in UTC.
     * @type {Date}
     * @memberof TaskResource
     */
    updatedAt?: Date;
    /**
     * 
     * @type {number}
     * @memberof TaskResource
     */
    id?: number;
}

/**
 * Check if a given object implements the TaskResource interface.
 */
export function instanceOfTaskResource(value: object): value is TaskResource {
    if (!('title' in value) || value['title'] === undefined) return false;
    return true;
}

export function TaskResourceFromJSON(json: any): TaskResource {
    return TaskResourceFromJSONTyped(json, false);
}

export function TaskResourceFromJSONTyped(json: any, ignoreDiscriminator: boolean): TaskResource {
    if (json == null) {
        return json;
    }
    return {
        
        'title': json['title'],
        'description': json['description'] == null ? undefined : json['description'],
        'instructions': json['instructions'] == null ? undefined : json['instructions'],
        'formId': json['form_id'] == null ? undefined : json['form_id'],
        'label': json['label'] == null ? undefined : json['label'],
        'createdAt': json['created_at'] == null ? undefined : (new Date(json['created_at'])),
        'updatedAt': json['updated_at'] == null ? undefined : (new Date(json['updated_at'])),
        'id': json['id'] == null ? undefined : json['id'],
    };
}

export function TaskResourceToJSON(json: any): TaskResource {
    return TaskResourceToJSONTyped(json, false);
}

export function TaskResourceToJSONTyped(value?: TaskResource | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'title': value['title'],
        'description': value['description'],
        'instructions': value['instructions'],
        'form_id': value['formId'],
        'label': value['label'],
        'created_at': value['createdAt'] == null ? undefined : ((value['createdAt']).toISOString()),
        'updated_at': value['updatedAt'] == null ? undefined : ((value['updatedAt']).toISOString()),
        'id': value['id'],
    };
}

