/* tslint:disable */
/* eslint-disable */
/**
 * PERSCOM Personnel Management System API
 * The PERSCOM API describes how to interact and manipulate your PERSCOM data available at https://perscom.io. The API provides a powerful interface to allow for third-party collaboration and integration with your PERSCOM Dashboard.
 *
 * The version of the OpenAPI document: v2
 * Contact: support@deschutesdesigngroup.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TrainingRecord
 */
export interface TrainingRecord {
    /**
     * 
     * @type {number}
     * @memberof TrainingRecord
     */
    userId: number;
    /**
     * 
     * @type {number}
     * @memberof TrainingRecord
     */
    instructorId?: number;
    /**
     * 
     * @type {number}
     * @memberof TrainingRecord
     */
    documentId?: number | null;
    /**
     * 
     * @type {number}
     * @memberof TrainingRecord
     */
    authorId?: number | null;
    /**
     * Supports HTML.
     * @type {string}
     * @memberof TrainingRecord
     */
    text?: string | null;
}

/**
 * Check if a given object implements the TrainingRecord interface.
 */
export function instanceOfTrainingRecord(value: object): value is TrainingRecord {
    if (!('userId' in value) || value['userId'] === undefined) return false;
    return true;
}

export function TrainingRecordFromJSON(json: any): TrainingRecord {
    return TrainingRecordFromJSONTyped(json, false);
}

export function TrainingRecordFromJSONTyped(json: any, ignoreDiscriminator: boolean): TrainingRecord {
    if (json == null) {
        return json;
    }
    return {
        
        'userId': json['user_id'],
        'instructorId': json['instructor_id'] == null ? undefined : json['instructor_id'],
        'documentId': json['document_id'] == null ? undefined : json['document_id'],
        'authorId': json['author_id'] == null ? undefined : json['author_id'],
        'text': json['text'] == null ? undefined : json['text'],
    };
}

export function TrainingRecordToJSON(json: any): TrainingRecord {
    return TrainingRecordToJSONTyped(json, false);
}

export function TrainingRecordToJSONTyped(value?: TrainingRecord | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'user_id': value['userId'],
        'instructor_id': value['instructorId'],
        'document_id': value['documentId'],
        'author_id': value['authorId'],
        'text': value['text'],
    };
}

