/* tslint:disable */
/* eslint-disable */
/**
 * PERSCOM Personnel Management System API
 * The PERSCOM API describes how to interact and manipulate your PERSCOM data available at https://perscom.io. The API provides a powerful interface to allow for third-party collaboration and integration with your PERSCOM Dashboard.
 *
 * The version of the OpenAPI document: v2
 * Contact: support@deschutesdesigngroup.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface VersionCategoriesCategoryAwardsDetachDelete200Response
 */
export interface VersionCategoriesCategoryAwardsDetachDelete200Response {
    /**
     * 
     * @type {Array<number>}
     * @memberof VersionCategoriesCategoryAwardsDetachDelete200Response
     */
    detached?: Array<number>;
}

/**
 * Check if a given object implements the VersionCategoriesCategoryAwardsDetachDelete200Response interface.
 */
export function instanceOfVersionCategoriesCategoryAwardsDetachDelete200Response(value: object): value is VersionCategoriesCategoryAwardsDetachDelete200Response {
    return true;
}

export function VersionCategoriesCategoryAwardsDetachDelete200ResponseFromJSON(json: any): VersionCategoriesCategoryAwardsDetachDelete200Response {
    return VersionCategoriesCategoryAwardsDetachDelete200ResponseFromJSONTyped(json, false);
}

export function VersionCategoriesCategoryAwardsDetachDelete200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): VersionCategoriesCategoryAwardsDetachDelete200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'detached': json['detached'] == null ? undefined : json['detached'],
    };
}

export function VersionCategoriesCategoryAwardsDetachDelete200ResponseToJSON(json: any): VersionCategoriesCategoryAwardsDetachDelete200Response {
    return VersionCategoriesCategoryAwardsDetachDelete200ResponseToJSONTyped(json, false);
}

export function VersionCategoriesCategoryAwardsDetachDelete200ResponseToJSONTyped(value?: VersionCategoriesCategoryAwardsDetachDelete200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'detached': value['detached'],
    };
}

