/* tslint:disable */
/* eslint-disable */
/**
 * PERSCOM Personnel Management System API
 * The PERSCOM API describes how to interact and manipulate your PERSCOM data available at https://perscom.io. The API provides a powerful interface to allow for third-party collaboration and integration with your PERSCOM Dashboard.
 *
 * The version of the OpenAPI document: v2
 * Contact: support@deschutesdesigngroup.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ResourceLinks } from './ResourceLinks';
import {
    ResourceLinksFromJSON,
    ResourceLinksFromJSONTyped,
    ResourceLinksToJSON,
    ResourceLinksToJSONTyped,
} from './ResourceLinks';
import type { EventResource } from './EventResource';
import {
    EventResourceFromJSON,
    EventResourceFromJSONTyped,
    EventResourceToJSON,
    EventResourceToJSONTyped,
} from './EventResource';
import type { ResourceMeta } from './ResourceMeta';
import {
    ResourceMetaFromJSON,
    ResourceMetaFromJSONTyped,
    ResourceMetaToJSON,
    ResourceMetaToJSONTyped,
} from './ResourceMeta';

/**
 * 
 * @export
 * @interface VersionEventsGet200Response
 */
export interface VersionEventsGet200Response {
    /**
     * 
     * @type {Array<EventResource>}
     * @memberof VersionEventsGet200Response
     */
    data?: Array<EventResource>;
    /**
     * 
     * @type {ResourceLinks}
     * @memberof VersionEventsGet200Response
     */
    links?: ResourceLinks;
    /**
     * 
     * @type {ResourceMeta}
     * @memberof VersionEventsGet200Response
     */
    meta?: ResourceMeta;
}

/**
 * Check if a given object implements the VersionEventsGet200Response interface.
 */
export function instanceOfVersionEventsGet200Response(value: object): value is VersionEventsGet200Response {
    return true;
}

export function VersionEventsGet200ResponseFromJSON(json: any): VersionEventsGet200Response {
    return VersionEventsGet200ResponseFromJSONTyped(json, false);
}

export function VersionEventsGet200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): VersionEventsGet200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'] == null ? undefined : ((json['data'] as Array<any>).map(EventResourceFromJSON)),
        'links': json['links'] == null ? undefined : ResourceLinksFromJSON(json['links']),
        'meta': json['meta'] == null ? undefined : ResourceMetaFromJSON(json['meta']),
    };
}

export function VersionEventsGet200ResponseToJSON(json: any): VersionEventsGet200Response {
    return VersionEventsGet200ResponseToJSONTyped(json, false);
}

export function VersionEventsGet200ResponseToJSONTyped(value?: VersionEventsGet200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': value['data'] == null ? undefined : ((value['data'] as Array<any>).map(EventResourceToJSON)),
        'links': ResourceLinksToJSON(value['links']),
        'meta': ResourceMetaToJSON(value['meta']),
    };
}

