/* tslint:disable */
/* eslint-disable */
/**
 * PERSCOM Personnel Management System API
 * The PERSCOM API describes how to interact and manipulate your PERSCOM data available at https://perscom.io. The API provides a powerful interface to allow for third-party collaboration and integration with your PERSCOM Dashboard.
 *
 * The version of the OpenAPI document: v2
 * Contact: support@deschutesdesigngroup.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { QualificationResource } from './QualificationResource';
import {
    QualificationResourceFromJSON,
    QualificationResourceFromJSONTyped,
    QualificationResourceToJSON,
    QualificationResourceToJSONTyped,
} from './QualificationResource';

/**
 * 
 * @export
 * @interface VersionCategoriesCategoryQualificationsBatchPost200Response
 */
export interface VersionCategoriesCategoryQualificationsBatchPost200Response {
    /**
     * 
     * @type {Array<QualificationResource>}
     * @memberof VersionCategoriesCategoryQualificationsBatchPost200Response
     */
    data?: Array<QualificationResource>;
}

/**
 * Check if a given object implements the VersionCategoriesCategoryQualificationsBatchPost200Response interface.
 */
export function instanceOfVersionCategoriesCategoryQualificationsBatchPost200Response(value: object): value is VersionCategoriesCategoryQualificationsBatchPost200Response {
    return true;
}

export function VersionCategoriesCategoryQualificationsBatchPost200ResponseFromJSON(json: any): VersionCategoriesCategoryQualificationsBatchPost200Response {
    return VersionCategoriesCategoryQualificationsBatchPost200ResponseFromJSONTyped(json, false);
}

export function VersionCategoriesCategoryQualificationsBatchPost200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): VersionCategoriesCategoryQualificationsBatchPost200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'] == null ? undefined : ((json['data'] as Array<any>).map(QualificationResourceFromJSON)),
    };
}

export function VersionCategoriesCategoryQualificationsBatchPost200ResponseToJSON(json: any): VersionCategoriesCategoryQualificationsBatchPost200Response {
    return VersionCategoriesCategoryQualificationsBatchPost200ResponseToJSONTyped(json, false);
}

export function VersionCategoriesCategoryQualificationsBatchPost200ResponseToJSONTyped(value?: VersionCategoriesCategoryQualificationsBatchPost200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': value['data'] == null ? undefined : ((value['data'] as Array<any>).map(QualificationResourceToJSON)),
    };
}

