/* tslint:disable */
/* eslint-disable */
/**
 * PERSCOM Personnel Management System API
 * The PERSCOM API describes how to interact and manipulate your PERSCOM data available at https://perscom.io. The API provides a powerful interface to allow for third-party collaboration and integration with your PERSCOM Dashboard.
 *
 * The version of the OpenAPI document: v2
 * Contact: support@deschutesdesigngroup.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { EventResource } from './EventResource';
import {
    EventResourceFromJSON,
    EventResourceFromJSONTyped,
    EventResourceToJSON,
    EventResourceToJSONTyped,
} from './EventResource';

/**
 * 
 * @export
 * @interface VersionEventsBatchPost200Response
 */
export interface VersionEventsBatchPost200Response {
    /**
     * 
     * @type {Array<EventResource>}
     * @memberof VersionEventsBatchPost200Response
     */
    data?: Array<EventResource>;
}

/**
 * Check if a given object implements the VersionEventsBatchPost200Response interface.
 */
export function instanceOfVersionEventsBatchPost200Response(value: object): value is VersionEventsBatchPost200Response {
    return true;
}

export function VersionEventsBatchPost200ResponseFromJSON(json: any): VersionEventsBatchPost200Response {
    return VersionEventsBatchPost200ResponseFromJSONTyped(json, false);
}

export function VersionEventsBatchPost200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): VersionEventsBatchPost200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'] == null ? undefined : ((json['data'] as Array<any>).map(EventResourceFromJSON)),
    };
}

export function VersionEventsBatchPost200ResponseToJSON(json: any): VersionEventsBatchPost200Response {
    return VersionEventsBatchPost200ResponseToJSONTyped(json, false);
}

export function VersionEventsBatchPost200ResponseToJSONTyped(value?: VersionEventsBatchPost200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': value['data'] == null ? undefined : ((value['data'] as Array<any>).map(EventResourceToJSON)),
    };
}

