/* tslint:disable */
/* eslint-disable */
/**
 * PERSCOM Personnel Management System API
 * The PERSCOM API describes how to interact and manipulate your PERSCOM data available at https://perscom.io. The API provides a powerful interface to allow for third-party collaboration and integration with your PERSCOM Dashboard.
 *
 * The version of the OpenAPI document: v2
 * Contact: support@deschutesdesigngroup.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ResourceLinks } from './ResourceLinks';
import {
    ResourceLinksFromJSON,
    ResourceLinksFromJSONTyped,
    ResourceLinksToJSON,
    ResourceLinksToJSONTyped,
} from './ResourceLinks';
import type { NewsfeedResource } from './NewsfeedResource';
import {
    NewsfeedResourceFromJSON,
    NewsfeedResourceFromJSONTyped,
    NewsfeedResourceToJSON,
    NewsfeedResourceToJSONTyped,
} from './NewsfeedResource';
import type { ResourceMeta } from './ResourceMeta';
import {
    ResourceMetaFromJSON,
    ResourceMetaFromJSONTyped,
    ResourceMetaToJSON,
    ResourceMetaToJSONTyped,
} from './ResourceMeta';

/**
 * 
 * @export
 * @interface VersionNewsfeedGet200Response
 */
export interface VersionNewsfeedGet200Response {
    /**
     * 
     * @type {Array<NewsfeedResource>}
     * @memberof VersionNewsfeedGet200Response
     */
    data?: Array<NewsfeedResource>;
    /**
     * 
     * @type {ResourceLinks}
     * @memberof VersionNewsfeedGet200Response
     */
    links?: ResourceLinks;
    /**
     * 
     * @type {ResourceMeta}
     * @memberof VersionNewsfeedGet200Response
     */
    meta?: ResourceMeta;
}

/**
 * Check if a given object implements the VersionNewsfeedGet200Response interface.
 */
export function instanceOfVersionNewsfeedGet200Response(value: object): value is VersionNewsfeedGet200Response {
    return true;
}

export function VersionNewsfeedGet200ResponseFromJSON(json: any): VersionNewsfeedGet200Response {
    return VersionNewsfeedGet200ResponseFromJSONTyped(json, false);
}

export function VersionNewsfeedGet200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): VersionNewsfeedGet200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'] == null ? undefined : ((json['data'] as Array<any>).map(NewsfeedResourceFromJSON)),
        'links': json['links'] == null ? undefined : ResourceLinksFromJSON(json['links']),
        'meta': json['meta'] == null ? undefined : ResourceMetaFromJSON(json['meta']),
    };
}

export function VersionNewsfeedGet200ResponseToJSON(json: any): VersionNewsfeedGet200Response {
    return VersionNewsfeedGet200ResponseToJSONTyped(json, false);
}

export function VersionNewsfeedGet200ResponseToJSONTyped(value?: VersionNewsfeedGet200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': value['data'] == null ? undefined : ((value['data'] as Array<any>).map(NewsfeedResourceToJSON)),
        'links': ResourceLinksToJSON(value['links']),
        'meta': ResourceMetaToJSON(value['meta']),
    };
}

