/* tslint:disable */
/* eslint-disable */
/**
 * PERSCOM Personnel Management System API
 * The PERSCOM API describes how to interact and manipulate your PERSCOM data available at https://perscom.io. The API provides a powerful interface to allow for third-party collaboration and integration with your PERSCOM Dashboard.
 *
 * The version of the OpenAPI document: v2
 * Contact: support@deschutesdesigngroup.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TrainingRecordResource } from './TrainingRecordResource';
import {
    TrainingRecordResourceFromJSON,
    TrainingRecordResourceFromJSONTyped,
    TrainingRecordResourceToJSON,
    TrainingRecordResourceToJSONTyped,
} from './TrainingRecordResource';

/**
 * 
 * @export
 * @interface VersionTrainingRecordsBatchPost200Response
 */
export interface VersionTrainingRecordsBatchPost200Response {
    /**
     * 
     * @type {Array<TrainingRecordResource>}
     * @memberof VersionTrainingRecordsBatchPost200Response
     */
    data?: Array<TrainingRecordResource>;
}

/**
 * Check if a given object implements the VersionTrainingRecordsBatchPost200Response interface.
 */
export function instanceOfVersionTrainingRecordsBatchPost200Response(value: object): value is VersionTrainingRecordsBatchPost200Response {
    return true;
}

export function VersionTrainingRecordsBatchPost200ResponseFromJSON(json: any): VersionTrainingRecordsBatchPost200Response {
    return VersionTrainingRecordsBatchPost200ResponseFromJSONTyped(json, false);
}

export function VersionTrainingRecordsBatchPost200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): VersionTrainingRecordsBatchPost200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'] == null ? undefined : ((json['data'] as Array<any>).map(TrainingRecordResourceFromJSON)),
    };
}

export function VersionTrainingRecordsBatchPost200ResponseToJSON(json: any): VersionTrainingRecordsBatchPost200Response {
    return VersionTrainingRecordsBatchPost200ResponseToJSONTyped(json, false);
}

export function VersionTrainingRecordsBatchPost200ResponseToJSONTyped(value?: VersionTrainingRecordsBatchPost200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': value['data'] == null ? undefined : ((value['data'] as Array<any>).map(TrainingRecordResourceToJSON)),
    };
}

