/* tslint:disable */
/* eslint-disable */
/**
 * PERSCOM Personnel Management System API
 * The PERSCOM API describes how to interact and manipulate your PERSCOM data available at https://perscom.io. The API provides a powerful interface to allow for third-party collaboration and integration with your PERSCOM Dashboard.
 *
 * The version of the OpenAPI document: v2
 * Contact: support@deschutesdesigngroup.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TaskResource } from './TaskResource';
import {
    TaskResourceFromJSON,
    TaskResourceFromJSONTyped,
    TaskResourceToJSON,
    TaskResourceToJSONTyped,
} from './TaskResource';
import type { ResourceLinks } from './ResourceLinks';
import {
    ResourceLinksFromJSON,
    ResourceLinksFromJSONTyped,
    ResourceLinksToJSON,
    ResourceLinksToJSONTyped,
} from './ResourceLinks';
import type { ResourceMeta } from './ResourceMeta';
import {
    ResourceMetaFromJSON,
    ResourceMetaFromJSONTyped,
    ResourceMetaToJSON,
    ResourceMetaToJSONTyped,
} from './ResourceMeta';

/**
 * 
 * @export
 * @interface VersionTasksGet200Response
 */
export interface VersionTasksGet200Response {
    /**
     * 
     * @type {Array<TaskResource>}
     * @memberof VersionTasksGet200Response
     */
    data?: Array<TaskResource>;
    /**
     * 
     * @type {ResourceLinks}
     * @memberof VersionTasksGet200Response
     */
    links?: ResourceLinks;
    /**
     * 
     * @type {ResourceMeta}
     * @memberof VersionTasksGet200Response
     */
    meta?: ResourceMeta;
}

/**
 * Check if a given object implements the VersionTasksGet200Response interface.
 */
export function instanceOfVersionTasksGet200Response(value: object): value is VersionTasksGet200Response {
    return true;
}

export function VersionTasksGet200ResponseFromJSON(json: any): VersionTasksGet200Response {
    return VersionTasksGet200ResponseFromJSONTyped(json, false);
}

export function VersionTasksGet200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): VersionTasksGet200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'] == null ? undefined : ((json['data'] as Array<any>).map(TaskResourceFromJSON)),
        'links': json['links'] == null ? undefined : ResourceLinksFromJSON(json['links']),
        'meta': json['meta'] == null ? undefined : ResourceMetaFromJSON(json['meta']),
    };
}

export function VersionTasksGet200ResponseToJSON(json: any): VersionTasksGet200Response {
    return VersionTasksGet200ResponseToJSONTyped(json, false);
}

export function VersionTasksGet200ResponseToJSONTyped(value?: VersionTasksGet200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': value['data'] == null ? undefined : ((value['data'] as Array<any>).map(TaskResourceToJSON)),
        'links': ResourceLinksToJSON(value['links']),
        'meta': ResourceMetaToJSON(value['meta']),
    };
}

