/* tslint:disable */
/* eslint-disable */
/**
 * PERSCOM Personnel Management System API
 * The PERSCOM API describes how to interact and manipulate your PERSCOM data available at https://perscom.io. The API provides a powerful interface to allow for third-party collaboration and integration with your PERSCOM Dashboard.
 *
 * The version of the OpenAPI document: v2
 * Contact: support@deschutesdesigngroup.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TaskResource } from './TaskResource';
import {
    TaskResourceFromJSON,
    TaskResourceFromJSONTyped,
    TaskResourceToJSON,
    TaskResourceToJSONTyped,
} from './TaskResource';

/**
 * 
 * @export
 * @interface VersionTasksBatchPost200Response
 */
export interface VersionTasksBatchPost200Response {
    /**
     * 
     * @type {Array<TaskResource>}
     * @memberof VersionTasksBatchPost200Response
     */
    data?: Array<TaskResource>;
}

/**
 * Check if a given object implements the VersionTasksBatchPost200Response interface.
 */
export function instanceOfVersionTasksBatchPost200Response(value: object): value is VersionTasksBatchPost200Response {
    return true;
}

export function VersionTasksBatchPost200ResponseFromJSON(json: any): VersionTasksBatchPost200Response {
    return VersionTasksBatchPost200ResponseFromJSONTyped(json, false);
}

export function VersionTasksBatchPost200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): VersionTasksBatchPost200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'] == null ? undefined : ((json['data'] as Array<any>).map(TaskResourceFromJSON)),
    };
}

export function VersionTasksBatchPost200ResponseToJSON(json: any): VersionTasksBatchPost200Response {
    return VersionTasksBatchPost200ResponseToJSONTyped(json, false);
}

export function VersionTasksBatchPost200ResponseToJSONTyped(value?: VersionTasksBatchPost200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': value['data'] == null ? undefined : ((value['data'] as Array<any>).map(TaskResourceToJSON)),
    };
}

