/* tslint:disable */
/* eslint-disable */
/**
 * PERSCOM Personnel Management System API
 * The PERSCOM API describes how to interact and manipulate your PERSCOM data available at https://perscom.io. The API provides a powerful interface to allow for third-party collaboration and integration with your PERSCOM Dashboard.
 *
 * The version of the OpenAPI document: v2
 * Contact: support@deschutesdesigngroup.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { FieldResource } from './FieldResource';
import {
    FieldResourceFromJSON,
    FieldResourceFromJSONTyped,
    FieldResourceToJSON,
    FieldResourceToJSONTyped,
} from './FieldResource';
import type { ResourceLinks } from './ResourceLinks';
import {
    ResourceLinksFromJSON,
    ResourceLinksFromJSONTyped,
    ResourceLinksToJSON,
    ResourceLinksToJSONTyped,
} from './ResourceLinks';
import type { ResourceMeta } from './ResourceMeta';
import {
    ResourceMetaFromJSON,
    ResourceMetaFromJSONTyped,
    ResourceMetaToJSON,
    ResourceMetaToJSONTyped,
} from './ResourceMeta';

/**
 * 
 * @export
 * @interface VersionFormsFormFieldsGet200Response
 */
export interface VersionFormsFormFieldsGet200Response {
    /**
     * 
     * @type {Array<FieldResource>}
     * @memberof VersionFormsFormFieldsGet200Response
     */
    data?: Array<FieldResource>;
    /**
     * 
     * @type {ResourceLinks}
     * @memberof VersionFormsFormFieldsGet200Response
     */
    links?: ResourceLinks;
    /**
     * 
     * @type {ResourceMeta}
     * @memberof VersionFormsFormFieldsGet200Response
     */
    meta?: ResourceMeta;
}

/**
 * Check if a given object implements the VersionFormsFormFieldsGet200Response interface.
 */
export function instanceOfVersionFormsFormFieldsGet200Response(value: object): value is VersionFormsFormFieldsGet200Response {
    return true;
}

export function VersionFormsFormFieldsGet200ResponseFromJSON(json: any): VersionFormsFormFieldsGet200Response {
    return VersionFormsFormFieldsGet200ResponseFromJSONTyped(json, false);
}

export function VersionFormsFormFieldsGet200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): VersionFormsFormFieldsGet200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'] == null ? undefined : ((json['data'] as Array<any>).map(FieldResourceFromJSON)),
        'links': json['links'] == null ? undefined : ResourceLinksFromJSON(json['links']),
        'meta': json['meta'] == null ? undefined : ResourceMetaFromJSON(json['meta']),
    };
}

export function VersionFormsFormFieldsGet200ResponseToJSON(json: any): VersionFormsFormFieldsGet200Response {
    return VersionFormsFormFieldsGet200ResponseToJSONTyped(json, false);
}

export function VersionFormsFormFieldsGet200ResponseToJSONTyped(value?: VersionFormsFormFieldsGet200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': value['data'] == null ? undefined : ((value['data'] as Array<any>).map(FieldResourceToJSON)),
        'links': ResourceLinksToJSON(value['links']),
        'meta': ResourceMetaToJSON(value['meta']),
    };
}

