/* tslint:disable */
/* eslint-disable */
/**
 * PERSCOM Personnel Management System API
 * The PERSCOM API describes how to interact and manipulate your PERSCOM data available at https://perscom.io. The API provides a powerful interface to allow for third-party collaboration and integration with your PERSCOM Dashboard.
 *
 * The version of the OpenAPI document: v2
 * Contact: support@deschutesdesigngroup.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Task } from './Task';
import {
    TaskFromJSON,
    TaskFromJSONTyped,
    TaskToJSON,
    TaskToJSONTyped,
} from './Task';

/**
 * 
 * @export
 * @interface VersionTasksBatchPatchRequestResources
 */
export interface VersionTasksBatchPatchRequestResources {
    /**
     * 
     * @type {Task}
     * @memberof VersionTasksBatchPatchRequestResources
     */
    key?: Task;
}

/**
 * Check if a given object implements the VersionTasksBatchPatchRequestResources interface.
 */
export function instanceOfVersionTasksBatchPatchRequestResources(value: object): value is VersionTasksBatchPatchRequestResources {
    return true;
}

export function VersionTasksBatchPatchRequestResourcesFromJSON(json: any): VersionTasksBatchPatchRequestResources {
    return VersionTasksBatchPatchRequestResourcesFromJSONTyped(json, false);
}

export function VersionTasksBatchPatchRequestResourcesFromJSONTyped(json: any, ignoreDiscriminator: boolean): VersionTasksBatchPatchRequestResources {
    if (json == null) {
        return json;
    }
    return {
        
        'key': json['{key}'] == null ? undefined : TaskFromJSON(json['{key}']),
    };
}

export function VersionTasksBatchPatchRequestResourcesToJSON(json: any): VersionTasksBatchPatchRequestResources {
    return VersionTasksBatchPatchRequestResourcesToJSONTyped(json, false);
}

export function VersionTasksBatchPatchRequestResourcesToJSONTyped(value?: VersionTasksBatchPatchRequestResources | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        '{key}': TaskToJSON(value['key']),
    };
}

