/* tslint:disable */
/* eslint-disable */
/**
 * PERSCOM Personnel Management System API
 * The PERSCOM API describes how to interact and manipulate your PERSCOM data available at https://perscom.io. The API provides a powerful interface to allow for third-party collaboration and integration with your PERSCOM Dashboard.
 *
 * The version of the OpenAPI document: v2
 * Contact: support@deschutesdesigngroup.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { FormResource } from './FormResource';
import {
    FormResourceFromJSON,
    FormResourceFromJSONTyped,
    FormResourceToJSON,
    FormResourceToJSONTyped,
} from './FormResource';

/**
 * 
 * @export
 * @interface VersionCategoriesCategoryFormsBatchPost200Response
 */
export interface VersionCategoriesCategoryFormsBatchPost200Response {
    /**
     * 
     * @type {Array<FormResource>}
     * @memberof VersionCategoriesCategoryFormsBatchPost200Response
     */
    data?: Array<FormResource>;
}

/**
 * Check if a given object implements the VersionCategoriesCategoryFormsBatchPost200Response interface.
 */
export function instanceOfVersionCategoriesCategoryFormsBatchPost200Response(value: object): value is VersionCategoriesCategoryFormsBatchPost200Response {
    return true;
}

export function VersionCategoriesCategoryFormsBatchPost200ResponseFromJSON(json: any): VersionCategoriesCategoryFormsBatchPost200Response {
    return VersionCategoriesCategoryFormsBatchPost200ResponseFromJSONTyped(json, false);
}

export function VersionCategoriesCategoryFormsBatchPost200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): VersionCategoriesCategoryFormsBatchPost200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'] == null ? undefined : ((json['data'] as Array<any>).map(FormResourceFromJSON)),
    };
}

export function VersionCategoriesCategoryFormsBatchPost200ResponseToJSON(json: any): VersionCategoriesCategoryFormsBatchPost200Response {
    return VersionCategoriesCategoryFormsBatchPost200ResponseToJSONTyped(json, false);
}

export function VersionCategoriesCategoryFormsBatchPost200ResponseToJSONTyped(value?: VersionCategoriesCategoryFormsBatchPost200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': value['data'] == null ? undefined : ((value['data'] as Array<any>).map(FormResourceToJSON)),
    };
}

