/* tslint:disable */
/* eslint-disable */
/**
 * PERSCOM Personnel Management System API
 * The PERSCOM API describes how to interact and manipulate your PERSCOM data available at https://perscom.io. The API provides a powerful interface to allow for third-party collaboration and integration with your PERSCOM Dashboard.
 *
 * The version of the OpenAPI document: v2
 * Contact: support@deschutesdesigngroup.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SpecialtyResource } from './SpecialtyResource';
import {
    SpecialtyResourceFromJSON,
    SpecialtyResourceFromJSONTyped,
    SpecialtyResourceToJSON,
    SpecialtyResourceToJSONTyped,
} from './SpecialtyResource';
import type { ResourceLinks } from './ResourceLinks';
import {
    ResourceLinksFromJSON,
    ResourceLinksFromJSONTyped,
    ResourceLinksToJSON,
    ResourceLinksToJSONTyped,
} from './ResourceLinks';
import type { ResourceMeta } from './ResourceMeta';
import {
    ResourceMetaFromJSON,
    ResourceMetaFromJSONTyped,
    ResourceMetaToJSON,
    ResourceMetaToJSONTyped,
} from './ResourceMeta';

/**
 * 
 * @export
 * @interface VersionSpecialtiesGet200Response
 */
export interface VersionSpecialtiesGet200Response {
    /**
     * 
     * @type {Array<SpecialtyResource>}
     * @memberof VersionSpecialtiesGet200Response
     */
    data?: Array<SpecialtyResource>;
    /**
     * 
     * @type {ResourceLinks}
     * @memberof VersionSpecialtiesGet200Response
     */
    links?: ResourceLinks;
    /**
     * 
     * @type {ResourceMeta}
     * @memberof VersionSpecialtiesGet200Response
     */
    meta?: ResourceMeta;
}

/**
 * Check if a given object implements the VersionSpecialtiesGet200Response interface.
 */
export function instanceOfVersionSpecialtiesGet200Response(value: object): value is VersionSpecialtiesGet200Response {
    return true;
}

export function VersionSpecialtiesGet200ResponseFromJSON(json: any): VersionSpecialtiesGet200Response {
    return VersionSpecialtiesGet200ResponseFromJSONTyped(json, false);
}

export function VersionSpecialtiesGet200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): VersionSpecialtiesGet200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'] == null ? undefined : ((json['data'] as Array<any>).map(SpecialtyResourceFromJSON)),
        'links': json['links'] == null ? undefined : ResourceLinksFromJSON(json['links']),
        'meta': json['meta'] == null ? undefined : ResourceMetaFromJSON(json['meta']),
    };
}

export function VersionSpecialtiesGet200ResponseToJSON(json: any): VersionSpecialtiesGet200Response {
    return VersionSpecialtiesGet200ResponseToJSONTyped(json, false);
}

export function VersionSpecialtiesGet200ResponseToJSONTyped(value?: VersionSpecialtiesGet200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': value['data'] == null ? undefined : ((value['data'] as Array<any>).map(SpecialtyResourceToJSON)),
        'links': ResourceLinksToJSON(value['links']),
        'meta': ResourceMetaToJSON(value['meta']),
    };
}

