/* tslint:disable */
/* eslint-disable */
/**
 * PERSCOM Personnel Management System API
 * The PERSCOM API describes how to interact and manipulate your PERSCOM data available at https://perscom.io. The API provides a powerful interface to allow for third-party collaboration and integration with your PERSCOM Dashboard.
 *
 * The version of the OpenAPI document: v2
 * Contact: support@deschutesdesigngroup.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AttachmentResource } from './AttachmentResource';
import {
    AttachmentResourceFromJSON,
    AttachmentResourceFromJSONTyped,
    AttachmentResourceToJSON,
    AttachmentResourceToJSONTyped,
} from './AttachmentResource';

/**
 * 
 * @export
 * @interface VersionAttachmentsBatchPost200Response
 */
export interface VersionAttachmentsBatchPost200Response {
    /**
     * 
     * @type {Array<AttachmentResource>}
     * @memberof VersionAttachmentsBatchPost200Response
     */
    data?: Array<AttachmentResource>;
}

/**
 * Check if a given object implements the VersionAttachmentsBatchPost200Response interface.
 */
export function instanceOfVersionAttachmentsBatchPost200Response(value: object): value is VersionAttachmentsBatchPost200Response {
    return true;
}

export function VersionAttachmentsBatchPost200ResponseFromJSON(json: any): VersionAttachmentsBatchPost200Response {
    return VersionAttachmentsBatchPost200ResponseFromJSONTyped(json, false);
}

export function VersionAttachmentsBatchPost200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): VersionAttachmentsBatchPost200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'] == null ? undefined : ((json['data'] as Array<any>).map(AttachmentResourceFromJSON)),
    };
}

export function VersionAttachmentsBatchPost200ResponseToJSON(json: any): VersionAttachmentsBatchPost200Response {
    return VersionAttachmentsBatchPost200ResponseToJSONTyped(json, false);
}

export function VersionAttachmentsBatchPost200ResponseToJSONTyped(value?: VersionAttachmentsBatchPost200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': value['data'] == null ? undefined : ((value['data'] as Array<any>).map(AttachmentResourceToJSON)),
    };
}

