/* tslint:disable */
/* eslint-disable */
/**
 * PERSCOM Personnel Management System API
 * The PERSCOM API describes how to interact and manipulate your PERSCOM data available at https://perscom.io. The API provides a powerful interface to allow for third-party collaboration and integration with your PERSCOM Dashboard.
 *
 * The version of the OpenAPI document: v2
 * Contact: support@deschutesdesigngroup.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ResourceLinks } from './ResourceLinks';
import {
    ResourceLinksFromJSON,
    ResourceLinksFromJSONTyped,
    ResourceLinksToJSON,
    ResourceLinksToJSONTyped,
} from './ResourceLinks';
import type { StatusResource } from './StatusResource';
import {
    StatusResourceFromJSON,
    StatusResourceFromJSONTyped,
    StatusResourceToJSON,
    StatusResourceToJSONTyped,
} from './StatusResource';
import type { ResourceMeta } from './ResourceMeta';
import {
    ResourceMetaFromJSON,
    ResourceMetaFromJSONTyped,
    ResourceMetaToJSON,
    ResourceMetaToJSONTyped,
} from './ResourceMeta';

/**
 * 
 * @export
 * @interface VersionStatusesGet200Response
 */
export interface VersionStatusesGet200Response {
    /**
     * 
     * @type {Array<StatusResource>}
     * @memberof VersionStatusesGet200Response
     */
    data?: Array<StatusResource>;
    /**
     * 
     * @type {ResourceLinks}
     * @memberof VersionStatusesGet200Response
     */
    links?: ResourceLinks;
    /**
     * 
     * @type {ResourceMeta}
     * @memberof VersionStatusesGet200Response
     */
    meta?: ResourceMeta;
}

/**
 * Check if a given object implements the VersionStatusesGet200Response interface.
 */
export function instanceOfVersionStatusesGet200Response(value: object): value is VersionStatusesGet200Response {
    return true;
}

export function VersionStatusesGet200ResponseFromJSON(json: any): VersionStatusesGet200Response {
    return VersionStatusesGet200ResponseFromJSONTyped(json, false);
}

export function VersionStatusesGet200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): VersionStatusesGet200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'] == null ? undefined : ((json['data'] as Array<any>).map(StatusResourceFromJSON)),
        'links': json['links'] == null ? undefined : ResourceLinksFromJSON(json['links']),
        'meta': json['meta'] == null ? undefined : ResourceMetaFromJSON(json['meta']),
    };
}

export function VersionStatusesGet200ResponseToJSON(json: any): VersionStatusesGet200Response {
    return VersionStatusesGet200ResponseToJSONTyped(json, false);
}

export function VersionStatusesGet200ResponseToJSONTyped(value?: VersionStatusesGet200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': value['data'] == null ? undefined : ((value['data'] as Array<any>).map(StatusResourceToJSON)),
        'links': ResourceLinksToJSON(value['links']),
        'meta': ResourceMetaToJSON(value['meta']),
    };
}

