/* tslint:disable */
/* eslint-disable */
/**
 * PERSCOM Personnel Management System API
 * The PERSCOM API describes how to interact and manipulate your PERSCOM data available at https://perscom.io. The API provides a powerful interface to allow for third-party collaboration and integration with your PERSCOM Dashboard.
 *
 * The version of the OpenAPI document: v2
 * Contact: support@deschutesdesigngroup.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { VersionFormsFormSubmissionsBatchPatchRequestResources } from './VersionFormsFormSubmissionsBatchPatchRequestResources';
import {
    VersionFormsFormSubmissionsBatchPatchRequestResourcesFromJSON,
    VersionFormsFormSubmissionsBatchPatchRequestResourcesFromJSONTyped,
    VersionFormsFormSubmissionsBatchPatchRequestResourcesToJSON,
    VersionFormsFormSubmissionsBatchPatchRequestResourcesToJSONTyped,
} from './VersionFormsFormSubmissionsBatchPatchRequestResources';

/**
 * 
 * @export
 * @interface VersionFormsFormSubmissionsBatchPatchRequest
 */
export interface VersionFormsFormSubmissionsBatchPatchRequest {
    /**
     * 
     * @type {VersionFormsFormSubmissionsBatchPatchRequestResources}
     * @memberof VersionFormsFormSubmissionsBatchPatchRequest
     */
    resources?: VersionFormsFormSubmissionsBatchPatchRequestResources;
}

/**
 * Check if a given object implements the VersionFormsFormSubmissionsBatchPatchRequest interface.
 */
export function instanceOfVersionFormsFormSubmissionsBatchPatchRequest(value: object): value is VersionFormsFormSubmissionsBatchPatchRequest {
    return true;
}

export function VersionFormsFormSubmissionsBatchPatchRequestFromJSON(json: any): VersionFormsFormSubmissionsBatchPatchRequest {
    return VersionFormsFormSubmissionsBatchPatchRequestFromJSONTyped(json, false);
}

export function VersionFormsFormSubmissionsBatchPatchRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): VersionFormsFormSubmissionsBatchPatchRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'resources': json['resources'] == null ? undefined : VersionFormsFormSubmissionsBatchPatchRequestResourcesFromJSON(json['resources']),
    };
}

export function VersionFormsFormSubmissionsBatchPatchRequestToJSON(json: any): VersionFormsFormSubmissionsBatchPatchRequest {
    return VersionFormsFormSubmissionsBatchPatchRequestToJSONTyped(json, false);
}

export function VersionFormsFormSubmissionsBatchPatchRequestToJSONTyped(value?: VersionFormsFormSubmissionsBatchPatchRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'resources': VersionFormsFormSubmissionsBatchPatchRequestResourcesToJSON(value['resources']),
    };
}

