/* tslint:disable */
/* eslint-disable */
/**
 * PERSCOM Personnel Management System API
 * The PERSCOM API describes how to interact and manipulate your PERSCOM data available at https://perscom.io. The API provides a powerful interface to allow for third-party collaboration and integration with your PERSCOM Dashboard.
 *
 * The version of the OpenAPI document: v2
 * Contact: support@deschutesdesigngroup.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { FieldResource } from './FieldResource';
import {
    FieldResourceFromJSON,
    FieldResourceFromJSONTyped,
    FieldResourceToJSON,
    FieldResourceToJSONTyped,
} from './FieldResource';

/**
 * 
 * @export
 * @interface VersionFormsFormFieldsBatchPost200Response
 */
export interface VersionFormsFormFieldsBatchPost200Response {
    /**
     * 
     * @type {Array<FieldResource>}
     * @memberof VersionFormsFormFieldsBatchPost200Response
     */
    data?: Array<FieldResource>;
}

/**
 * Check if a given object implements the VersionFormsFormFieldsBatchPost200Response interface.
 */
export function instanceOfVersionFormsFormFieldsBatchPost200Response(value: object): value is VersionFormsFormFieldsBatchPost200Response {
    return true;
}

export function VersionFormsFormFieldsBatchPost200ResponseFromJSON(json: any): VersionFormsFormFieldsBatchPost200Response {
    return VersionFormsFormFieldsBatchPost200ResponseFromJSONTyped(json, false);
}

export function VersionFormsFormFieldsBatchPost200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): VersionFormsFormFieldsBatchPost200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'] == null ? undefined : ((json['data'] as Array<any>).map(FieldResourceFromJSON)),
    };
}

export function VersionFormsFormFieldsBatchPost200ResponseToJSON(json: any): VersionFormsFormFieldsBatchPost200Response {
    return VersionFormsFormFieldsBatchPost200ResponseToJSONTyped(json, false);
}

export function VersionFormsFormFieldsBatchPost200ResponseToJSONTyped(value?: VersionFormsFormFieldsBatchPost200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': value['data'] == null ? undefined : ((value['data'] as Array<any>).map(FieldResourceToJSON)),
    };
}

