/* tslint:disable */
/* eslint-disable */
/**
 * PERSCOM Personnel Management System API
 * The PERSCOM API describes how to interact and manipulate your PERSCOM data available at https://perscom.io. The API provides a powerful interface to allow for third-party collaboration and integration with your PERSCOM Dashboard.
 *
 * The version of the OpenAPI document: v2
 * Contact: support@deschutesdesigngroup.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { RosterResource } from './RosterResource';
import {
    RosterResourceFromJSON,
    RosterResourceFromJSONTyped,
    RosterResourceToJSON,
    RosterResourceToJSONTyped,
} from './RosterResource';
import type { ResourceLinks } from './ResourceLinks';
import {
    ResourceLinksFromJSON,
    ResourceLinksFromJSONTyped,
    ResourceLinksToJSON,
    ResourceLinksToJSONTyped,
} from './ResourceLinks';
import type { ResourceMeta } from './ResourceMeta';
import {
    ResourceMetaFromJSON,
    ResourceMetaFromJSONTyped,
    ResourceMetaToJSON,
    ResourceMetaToJSONTyped,
} from './ResourceMeta';

/**
 * 
 * @export
 * @interface VersionRosterGet200Response
 */
export interface VersionRosterGet200Response {
    /**
     * 
     * @type {Array<RosterResource>}
     * @memberof VersionRosterGet200Response
     */
    data?: Array<RosterResource>;
    /**
     * 
     * @type {ResourceLinks}
     * @memberof VersionRosterGet200Response
     */
    links?: ResourceLinks;
    /**
     * 
     * @type {ResourceMeta}
     * @memberof VersionRosterGet200Response
     */
    meta?: ResourceMeta;
}

/**
 * Check if a given object implements the VersionRosterGet200Response interface.
 */
export function instanceOfVersionRosterGet200Response(value: object): value is VersionRosterGet200Response {
    return true;
}

export function VersionRosterGet200ResponseFromJSON(json: any): VersionRosterGet200Response {
    return VersionRosterGet200ResponseFromJSONTyped(json, false);
}

export function VersionRosterGet200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): VersionRosterGet200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'] == null ? undefined : ((json['data'] as Array<any>).map(RosterResourceFromJSON)),
        'links': json['links'] == null ? undefined : ResourceLinksFromJSON(json['links']),
        'meta': json['meta'] == null ? undefined : ResourceMetaFromJSON(json['meta']),
    };
}

export function VersionRosterGet200ResponseToJSON(json: any): VersionRosterGet200Response {
    return VersionRosterGet200ResponseToJSONTyped(json, false);
}

export function VersionRosterGet200ResponseToJSONTyped(value?: VersionRosterGet200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': value['data'] == null ? undefined : ((value['data'] as Array<any>).map(RosterResourceToJSON)),
        'links': ResourceLinksToJSON(value['links']),
        'meta': ResourceMetaToJSON(value['meta']),
    };
}

