/* tslint:disable */
/* eslint-disable */
/**
 * PERSCOM Personnel Management System API
 * The PERSCOM API describes how to interact and manipulate your PERSCOM data available at https://perscom.io. The API provides a powerful interface to allow for third-party collaboration and integration with your PERSCOM Dashboard.
 *
 * The version of the OpenAPI document: v2
 * Contact: support@deschutesdesigngroup.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { EventResource } from './EventResource';
import {
    EventResourceFromJSON,
    EventResourceFromJSONTyped,
    EventResourceToJSON,
    EventResourceToJSONTyped,
} from './EventResource';

/**
 * 
 * @export
 * @interface VersionEventsPost201Response
 */
export interface VersionEventsPost201Response {
    /**
     * 
     * @type {EventResource}
     * @memberof VersionEventsPost201Response
     */
    data?: EventResource;
}

/**
 * Check if a given object implements the VersionEventsPost201Response interface.
 */
export function instanceOfVersionEventsPost201Response(value: object): value is VersionEventsPost201Response {
    return true;
}

export function VersionEventsPost201ResponseFromJSON(json: any): VersionEventsPost201Response {
    return VersionEventsPost201ResponseFromJSONTyped(json, false);
}

export function VersionEventsPost201ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): VersionEventsPost201Response {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'] == null ? undefined : EventResourceFromJSON(json['data']),
    };
}

export function VersionEventsPost201ResponseToJSON(json: any): VersionEventsPost201Response {
    return VersionEventsPost201ResponseToJSONTyped(json, false);
}

export function VersionEventsPost201ResponseToJSONTyped(value?: VersionEventsPost201Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': EventResourceToJSON(value['data']),
    };
}

