/* tslint:disable */
/* eslint-disable */
/**
 * PERSCOM Personnel Management System API
 * The PERSCOM API describes how to interact and manipulate your PERSCOM data available at https://perscom.io. The API provides a powerful interface to allow for third-party collaboration and integration with your PERSCOM Dashboard.
 *
 * The version of the OpenAPI document: v2
 * Contact: support@deschutesdesigngroup.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ResourceLinks } from './ResourceLinks';
import {
    ResourceLinksFromJSON,
    ResourceLinksFromJSONTyped,
    ResourceLinksToJSON,
    ResourceLinksToJSONTyped,
} from './ResourceLinks';
import type { ResourceMeta } from './ResourceMeta';
import {
    ResourceMetaFromJSON,
    ResourceMetaFromJSONTyped,
    ResourceMetaToJSON,
    ResourceMetaToJSONTyped,
} from './ResourceMeta';
import type { SettingsResource } from './SettingsResource';
import {
    SettingsResourceFromJSON,
    SettingsResourceFromJSONTyped,
    SettingsResourceToJSON,
    SettingsResourceToJSONTyped,
} from './SettingsResource';

/**
 * 
 * @export
 * @interface VersionSettingsGet200Response
 */
export interface VersionSettingsGet200Response {
    /**
     * 
     * @type {Array<SettingsResource>}
     * @memberof VersionSettingsGet200Response
     */
    data?: Array<SettingsResource>;
    /**
     * 
     * @type {ResourceLinks}
     * @memberof VersionSettingsGet200Response
     */
    links?: ResourceLinks;
    /**
     * 
     * @type {ResourceMeta}
     * @memberof VersionSettingsGet200Response
     */
    meta?: ResourceMeta;
}

/**
 * Check if a given object implements the VersionSettingsGet200Response interface.
 */
export function instanceOfVersionSettingsGet200Response(value: object): value is VersionSettingsGet200Response {
    return true;
}

export function VersionSettingsGet200ResponseFromJSON(json: any): VersionSettingsGet200Response {
    return VersionSettingsGet200ResponseFromJSONTyped(json, false);
}

export function VersionSettingsGet200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): VersionSettingsGet200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'] == null ? undefined : ((json['data'] as Array<any>).map(SettingsResourceFromJSON)),
        'links': json['links'] == null ? undefined : ResourceLinksFromJSON(json['links']),
        'meta': json['meta'] == null ? undefined : ResourceMetaFromJSON(json['meta']),
    };
}

export function VersionSettingsGet200ResponseToJSON(json: any): VersionSettingsGet200Response {
    return VersionSettingsGet200ResponseToJSONTyped(json, false);
}

export function VersionSettingsGet200ResponseToJSONTyped(value?: VersionSettingsGet200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': value['data'] == null ? undefined : ((value['data'] as Array<any>).map(SettingsResourceToJSON)),
        'links': ResourceLinksToJSON(value['links']),
        'meta': ResourceMetaToJSON(value['meta']),
    };
}

