/* tslint:disable */
/* eslint-disable */
/**
 * PERSCOM Personnel Management System API
 * The PERSCOM API describes how to interact and manipulate your PERSCOM data available at https://perscom.io. The API provides a powerful interface to allow for third-party collaboration and integration with your PERSCOM Dashboard.
 *
 * The version of the OpenAPI document: v2
 * Contact: support@deschutesdesigngroup.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ResourceLinks } from './ResourceLinks';
import {
    ResourceLinksFromJSON,
    ResourceLinksFromJSONTyped,
    ResourceLinksToJSON,
    ResourceLinksToJSONTyped,
} from './ResourceLinks';
import type { CalendarResource } from './CalendarResource';
import {
    CalendarResourceFromJSON,
    CalendarResourceFromJSONTyped,
    CalendarResourceToJSON,
    CalendarResourceToJSONTyped,
} from './CalendarResource';
import type { ResourceMeta } from './ResourceMeta';
import {
    ResourceMetaFromJSON,
    ResourceMetaFromJSONTyped,
    ResourceMetaToJSON,
    ResourceMetaToJSONTyped,
} from './ResourceMeta';

/**
 * 
 * @export
 * @interface VersionCalendarsGet200Response
 */
export interface VersionCalendarsGet200Response {
    /**
     * 
     * @type {Array<CalendarResource>}
     * @memberof VersionCalendarsGet200Response
     */
    data?: Array<CalendarResource>;
    /**
     * 
     * @type {ResourceLinks}
     * @memberof VersionCalendarsGet200Response
     */
    links?: ResourceLinks;
    /**
     * 
     * @type {ResourceMeta}
     * @memberof VersionCalendarsGet200Response
     */
    meta?: ResourceMeta;
}

/**
 * Check if a given object implements the VersionCalendarsGet200Response interface.
 */
export function instanceOfVersionCalendarsGet200Response(value: object): value is VersionCalendarsGet200Response {
    return true;
}

export function VersionCalendarsGet200ResponseFromJSON(json: any): VersionCalendarsGet200Response {
    return VersionCalendarsGet200ResponseFromJSONTyped(json, false);
}

export function VersionCalendarsGet200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): VersionCalendarsGet200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'] == null ? undefined : ((json['data'] as Array<any>).map(CalendarResourceFromJSON)),
        'links': json['links'] == null ? undefined : ResourceLinksFromJSON(json['links']),
        'meta': json['meta'] == null ? undefined : ResourceMetaFromJSON(json['meta']),
    };
}

export function VersionCalendarsGet200ResponseToJSON(json: any): VersionCalendarsGet200Response {
    return VersionCalendarsGet200ResponseToJSONTyped(json, false);
}

export function VersionCalendarsGet200ResponseToJSONTyped(value?: VersionCalendarsGet200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': value['data'] == null ? undefined : ((value['data'] as Array<any>).map(CalendarResourceToJSON)),
        'links': ResourceLinksToJSON(value['links']),
        'meta': ResourceMetaToJSON(value['meta']),
    };
}

