/* tslint:disable */
/* eslint-disable */
/**
 * PERSCOM Personnel Management System API
 * The PERSCOM API describes how to interact and manipulate your PERSCOM data available at https://perscom.io. The API provides a powerful interface to allow for third-party collaboration and integration with your PERSCOM Dashboard.
 *
 * The version of the OpenAPI document: v2
 * Contact: support@deschutesdesigngroup.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface VersionAnnouncementsBatchDeleteRequest
 */
export interface VersionAnnouncementsBatchDeleteRequest {
    /**
     * 
     * @type {Array<number>}
     * @memberof VersionAnnouncementsBatchDeleteRequest
     */
    resources?: Array<number>;
}

/**
 * Check if a given object implements the VersionAnnouncementsBatchDeleteRequest interface.
 */
export function instanceOfVersionAnnouncementsBatchDeleteRequest(value: object): value is VersionAnnouncementsBatchDeleteRequest {
    return true;
}

export function VersionAnnouncementsBatchDeleteRequestFromJSON(json: any): VersionAnnouncementsBatchDeleteRequest {
    return VersionAnnouncementsBatchDeleteRequestFromJSONTyped(json, false);
}

export function VersionAnnouncementsBatchDeleteRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): VersionAnnouncementsBatchDeleteRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'resources': json['resources'] == null ? undefined : json['resources'],
    };
}

export function VersionAnnouncementsBatchDeleteRequestToJSON(json: any): VersionAnnouncementsBatchDeleteRequest {
    return VersionAnnouncementsBatchDeleteRequestToJSONTyped(json, false);
}

export function VersionAnnouncementsBatchDeleteRequestToJSONTyped(value?: VersionAnnouncementsBatchDeleteRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'resources': value['resources'],
    };
}

