/* tslint:disable */
/* eslint-disable */
/**
 * PERSCOM Personnel Management System API
 * The PERSCOM API describes how to interact and manipulate your PERSCOM data available at https://perscom.io. The API provides a powerful interface to allow for third-party collaboration and integration with your PERSCOM Dashboard.
 *
 * The version of the OpenAPI document: v2
 * Contact: support@deschutesdesigngroup.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AssignmentRecordResource } from './AssignmentRecordResource';
import {
    AssignmentRecordResourceFromJSON,
    AssignmentRecordResourceFromJSONTyped,
    AssignmentRecordResourceToJSON,
    AssignmentRecordResourceToJSONTyped,
} from './AssignmentRecordResource';
import type { ResourceLinks } from './ResourceLinks';
import {
    ResourceLinksFromJSON,
    ResourceLinksFromJSONTyped,
    ResourceLinksToJSON,
    ResourceLinksToJSONTyped,
} from './ResourceLinks';
import type { ResourceMeta } from './ResourceMeta';
import {
    ResourceMetaFromJSON,
    ResourceMetaFromJSONTyped,
    ResourceMetaToJSON,
    ResourceMetaToJSONTyped,
} from './ResourceMeta';

/**
 * 
 * @export
 * @interface VersionAssignmentRecordsGet200Response
 */
export interface VersionAssignmentRecordsGet200Response {
    /**
     * 
     * @type {Array<AssignmentRecordResource>}
     * @memberof VersionAssignmentRecordsGet200Response
     */
    data?: Array<AssignmentRecordResource>;
    /**
     * 
     * @type {ResourceLinks}
     * @memberof VersionAssignmentRecordsGet200Response
     */
    links?: ResourceLinks;
    /**
     * 
     * @type {ResourceMeta}
     * @memberof VersionAssignmentRecordsGet200Response
     */
    meta?: ResourceMeta;
}

/**
 * Check if a given object implements the VersionAssignmentRecordsGet200Response interface.
 */
export function instanceOfVersionAssignmentRecordsGet200Response(value: object): value is VersionAssignmentRecordsGet200Response {
    return true;
}

export function VersionAssignmentRecordsGet200ResponseFromJSON(json: any): VersionAssignmentRecordsGet200Response {
    return VersionAssignmentRecordsGet200ResponseFromJSONTyped(json, false);
}

export function VersionAssignmentRecordsGet200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): VersionAssignmentRecordsGet200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'] == null ? undefined : ((json['data'] as Array<any>).map(AssignmentRecordResourceFromJSON)),
        'links': json['links'] == null ? undefined : ResourceLinksFromJSON(json['links']),
        'meta': json['meta'] == null ? undefined : ResourceMetaFromJSON(json['meta']),
    };
}

export function VersionAssignmentRecordsGet200ResponseToJSON(json: any): VersionAssignmentRecordsGet200Response {
    return VersionAssignmentRecordsGet200ResponseToJSONTyped(json, false);
}

export function VersionAssignmentRecordsGet200ResponseToJSONTyped(value?: VersionAssignmentRecordsGet200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': value['data'] == null ? undefined : ((value['data'] as Array<any>).map(AssignmentRecordResourceToJSON)),
        'links': ResourceLinksToJSON(value['links']),
        'meta': ResourceMetaToJSON(value['meta']),
    };
}

