/* tslint:disable */
/* eslint-disable */
/**
 * PERSCOM Personnel Management System API
 * The PERSCOM API describes how to interact and manipulate your PERSCOM data available at https://perscom.io. The API provides a powerful interface to allow for third-party collaboration and integration with your PERSCOM Dashboard.
 *
 * The version of the OpenAPI document: v2
 * Contact: support@deschutesdesigngroup.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TrainingRecord } from './TrainingRecord';
import {
    TrainingRecordFromJSON,
    TrainingRecordFromJSONTyped,
    TrainingRecordToJSON,
    TrainingRecordToJSONTyped,
} from './TrainingRecord';

/**
 * 
 * @export
 * @interface VersionTrainingRecordsBatchPatchRequestResources
 */
export interface VersionTrainingRecordsBatchPatchRequestResources {
    /**
     * 
     * @type {TrainingRecord}
     * @memberof VersionTrainingRecordsBatchPatchRequestResources
     */
    key?: TrainingRecord;
}

/**
 * Check if a given object implements the VersionTrainingRecordsBatchPatchRequestResources interface.
 */
export function instanceOfVersionTrainingRecordsBatchPatchRequestResources(value: object): value is VersionTrainingRecordsBatchPatchRequestResources {
    return true;
}

export function VersionTrainingRecordsBatchPatchRequestResourcesFromJSON(json: any): VersionTrainingRecordsBatchPatchRequestResources {
    return VersionTrainingRecordsBatchPatchRequestResourcesFromJSONTyped(json, false);
}

export function VersionTrainingRecordsBatchPatchRequestResourcesFromJSONTyped(json: any, ignoreDiscriminator: boolean): VersionTrainingRecordsBatchPatchRequestResources {
    if (json == null) {
        return json;
    }
    return {
        
        'key': json['{key}'] == null ? undefined : TrainingRecordFromJSON(json['{key}']),
    };
}

export function VersionTrainingRecordsBatchPatchRequestResourcesToJSON(json: any): VersionTrainingRecordsBatchPatchRequestResources {
    return VersionTrainingRecordsBatchPatchRequestResourcesToJSONTyped(json, false);
}

export function VersionTrainingRecordsBatchPatchRequestResourcesToJSONTyped(value?: VersionTrainingRecordsBatchPatchRequestResources | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        '{key}': TrainingRecordToJSON(value['key']),
    };
}

