/* tslint:disable */
/* eslint-disable */
/**
 * PERSCOM Personnel Management System API
 * The PERSCOM API describes how to interact and manipulate your PERSCOM data available at https://perscom.io. The API provides a powerful interface to allow for third-party collaboration and integration with your PERSCOM Dashboard.
 *
 * The version of the OpenAPI document: v2
 * Contact: support@deschutesdesigngroup.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { VersionSpecialtiesBatchPatchRequestResources } from './VersionSpecialtiesBatchPatchRequestResources';
import {
    VersionSpecialtiesBatchPatchRequestResourcesFromJSON,
    VersionSpecialtiesBatchPatchRequestResourcesFromJSONTyped,
    VersionSpecialtiesBatchPatchRequestResourcesToJSON,
    VersionSpecialtiesBatchPatchRequestResourcesToJSONTyped,
} from './VersionSpecialtiesBatchPatchRequestResources';

/**
 * 
 * @export
 * @interface VersionSpecialtiesBatchPatchRequest
 */
export interface VersionSpecialtiesBatchPatchRequest {
    /**
     * 
     * @type {VersionSpecialtiesBatchPatchRequestResources}
     * @memberof VersionSpecialtiesBatchPatchRequest
     */
    resources?: VersionSpecialtiesBatchPatchRequestResources;
}

/**
 * Check if a given object implements the VersionSpecialtiesBatchPatchRequest interface.
 */
export function instanceOfVersionSpecialtiesBatchPatchRequest(value: object): value is VersionSpecialtiesBatchPatchRequest {
    return true;
}

export function VersionSpecialtiesBatchPatchRequestFromJSON(json: any): VersionSpecialtiesBatchPatchRequest {
    return VersionSpecialtiesBatchPatchRequestFromJSONTyped(json, false);
}

export function VersionSpecialtiesBatchPatchRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): VersionSpecialtiesBatchPatchRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'resources': json['resources'] == null ? undefined : VersionSpecialtiesBatchPatchRequestResourcesFromJSON(json['resources']),
    };
}

export function VersionSpecialtiesBatchPatchRequestToJSON(json: any): VersionSpecialtiesBatchPatchRequest {
    return VersionSpecialtiesBatchPatchRequestToJSONTyped(json, false);
}

export function VersionSpecialtiesBatchPatchRequestToJSONTyped(value?: VersionSpecialtiesBatchPatchRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'resources': VersionSpecialtiesBatchPatchRequestResourcesToJSON(value['resources']),
    };
}

