/* tslint:disable */
/* eslint-disable */
/**
 * PERSCOM Personnel Management System API
 * The PERSCOM API describes how to interact and manipulate your PERSCOM data available at https://perscom.io. The API provides a powerful interface to allow for third-party collaboration and integration with your PERSCOM Dashboard.
 *
 * The version of the OpenAPI document: v2
 * Contact: support@deschutesdesigngroup.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { GroupResource } from './GroupResource';
import {
    GroupResourceFromJSON,
    GroupResourceFromJSONTyped,
    GroupResourceToJSON,
    GroupResourceToJSONTyped,
} from './GroupResource';

/**
 * 
 * @export
 * @interface VersionGroupsBatchPost200Response
 */
export interface VersionGroupsBatchPost200Response {
    /**
     * 
     * @type {Array<GroupResource>}
     * @memberof VersionGroupsBatchPost200Response
     */
    data?: Array<GroupResource>;
}

/**
 * Check if a given object implements the VersionGroupsBatchPost200Response interface.
 */
export function instanceOfVersionGroupsBatchPost200Response(value: object): value is VersionGroupsBatchPost200Response {
    return true;
}

export function VersionGroupsBatchPost200ResponseFromJSON(json: any): VersionGroupsBatchPost200Response {
    return VersionGroupsBatchPost200ResponseFromJSONTyped(json, false);
}

export function VersionGroupsBatchPost200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): VersionGroupsBatchPost200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'] == null ? undefined : ((json['data'] as Array<any>).map(GroupResourceFromJSON)),
    };
}

export function VersionGroupsBatchPost200ResponseToJSON(json: any): VersionGroupsBatchPost200Response {
    return VersionGroupsBatchPost200ResponseToJSONTyped(json, false);
}

export function VersionGroupsBatchPost200ResponseToJSONTyped(value?: VersionGroupsBatchPost200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': value['data'] == null ? undefined : ((value['data'] as Array<any>).map(GroupResourceToJSON)),
    };
}

