/* tslint:disable */
/* eslint-disable */
/**
 * PERSCOM Personnel Management System API
 * The PERSCOM API describes how to interact and manipulate your PERSCOM data available at https://perscom.io. The API provides a powerful interface to allow for third-party collaboration and integration with your PERSCOM Dashboard.
 *
 * The version of the OpenAPI document: v2
 * Contact: support@deschutesdesigngroup.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Attachment } from './Attachment';
import {
    AttachmentFromJSON,
    AttachmentFromJSONTyped,
    AttachmentToJSON,
    AttachmentToJSONTyped,
} from './Attachment';

/**
 * 
 * @export
 * @interface VersionAttachmentsBatchPostRequest
 */
export interface VersionAttachmentsBatchPostRequest {
    /**
     * 
     * @type {Array<Attachment>}
     * @memberof VersionAttachmentsBatchPostRequest
     */
    resources?: Array<Attachment>;
}

/**
 * Check if a given object implements the VersionAttachmentsBatchPostRequest interface.
 */
export function instanceOfVersionAttachmentsBatchPostRequest(value: object): value is VersionAttachmentsBatchPostRequest {
    return true;
}

export function VersionAttachmentsBatchPostRequestFromJSON(json: any): VersionAttachmentsBatchPostRequest {
    return VersionAttachmentsBatchPostRequestFromJSONTyped(json, false);
}

export function VersionAttachmentsBatchPostRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): VersionAttachmentsBatchPostRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'resources': json['resources'] == null ? undefined : ((json['resources'] as Array<any>).map(AttachmentFromJSON)),
    };
}

export function VersionAttachmentsBatchPostRequestToJSON(json: any): VersionAttachmentsBatchPostRequest {
    return VersionAttachmentsBatchPostRequestToJSONTyped(json, false);
}

export function VersionAttachmentsBatchPostRequestToJSONTyped(value?: VersionAttachmentsBatchPostRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'resources': value['resources'] == null ? undefined : ((value['resources'] as Array<any>).map(AttachmentToJSON)),
    };
}

