/* tslint:disable */
/* eslint-disable */
/**
 * PERSCOM Personnel Management System API
 * The PERSCOM API describes how to interact and manipulate your PERSCOM data available at https://perscom.io. The API provides a powerful interface to allow for third-party collaboration and integration with your PERSCOM Dashboard.
 *
 * The version of the OpenAPI document: v2
 * Contact: support@deschutesdesigngroup.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface VersionCategoriesCategoryAwardsSyncPatch200Response
 */
export interface VersionCategoriesCategoryAwardsSyncPatch200Response {
    /**
     * 
     * @type {Array<number>}
     * @memberof VersionCategoriesCategoryAwardsSyncPatch200Response
     */
    attached?: Array<number>;
    /**
     * 
     * @type {Array<number>}
     * @memberof VersionCategoriesCategoryAwardsSyncPatch200Response
     */
    detached?: Array<number>;
    /**
     * 
     * @type {Array<number>}
     * @memberof VersionCategoriesCategoryAwardsSyncPatch200Response
     */
    updated?: Array<number>;
}

/**
 * Check if a given object implements the VersionCategoriesCategoryAwardsSyncPatch200Response interface.
 */
export function instanceOfVersionCategoriesCategoryAwardsSyncPatch200Response(value: object): value is VersionCategoriesCategoryAwardsSyncPatch200Response {
    return true;
}

export function VersionCategoriesCategoryAwardsSyncPatch200ResponseFromJSON(json: any): VersionCategoriesCategoryAwardsSyncPatch200Response {
    return VersionCategoriesCategoryAwardsSyncPatch200ResponseFromJSONTyped(json, false);
}

export function VersionCategoriesCategoryAwardsSyncPatch200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): VersionCategoriesCategoryAwardsSyncPatch200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'attached': json['attached'] == null ? undefined : json['attached'],
        'detached': json['detached'] == null ? undefined : json['detached'],
        'updated': json['updated'] == null ? undefined : json['updated'],
    };
}

export function VersionCategoriesCategoryAwardsSyncPatch200ResponseToJSON(json: any): VersionCategoriesCategoryAwardsSyncPatch200Response {
    return VersionCategoriesCategoryAwardsSyncPatch200ResponseToJSONTyped(json, false);
}

export function VersionCategoriesCategoryAwardsSyncPatch200ResponseToJSONTyped(value?: VersionCategoriesCategoryAwardsSyncPatch200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'attached': value['attached'],
        'detached': value['detached'],
        'updated': value['updated'],
    };
}

