/* tslint:disable */
/* eslint-disable */
/**
 * PERSCOM Personnel Management System API
 * The PERSCOM API describes how to interact and manipulate your PERSCOM data available at https://perscom.io. The API provides a powerful interface to allow for third-party collaboration and integration with your PERSCOM Dashboard.
 *
 * The version of the OpenAPI document: v2
 * Contact: support@deschutesdesigngroup.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { MessageResource } from './MessageResource';
import {
    MessageResourceFromJSON,
    MessageResourceFromJSONTyped,
    MessageResourceToJSON,
    MessageResourceToJSONTyped,
} from './MessageResource';

/**
 * 
 * @export
 * @interface VersionMessagesPost201Response
 */
export interface VersionMessagesPost201Response {
    /**
     * 
     * @type {MessageResource}
     * @memberof VersionMessagesPost201Response
     */
    data?: MessageResource;
}

/**
 * Check if a given object implements the VersionMessagesPost201Response interface.
 */
export function instanceOfVersionMessagesPost201Response(value: object): value is VersionMessagesPost201Response {
    return true;
}

export function VersionMessagesPost201ResponseFromJSON(json: any): VersionMessagesPost201Response {
    return VersionMessagesPost201ResponseFromJSONTyped(json, false);
}

export function VersionMessagesPost201ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): VersionMessagesPost201Response {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'] == null ? undefined : MessageResourceFromJSON(json['data']),
    };
}

export function VersionMessagesPost201ResponseToJSON(json: any): VersionMessagesPost201Response {
    return VersionMessagesPost201ResponseToJSONTyped(json, false);
}

export function VersionMessagesPost201ResponseToJSONTyped(value?: VersionMessagesPost201Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': MessageResourceToJSON(value['data']),
    };
}

