/* tslint:disable */
/* eslint-disable */
/**
 * PERSCOM Personnel Management System API
 * The PERSCOM API describes how to interact and manipulate your PERSCOM data available at https://perscom.io. The API provides a powerful interface to allow for third-party collaboration and integration with your PERSCOM Dashboard.
 *
 * The version of the OpenAPI document: v2
 * Contact: support@deschutesdesigngroup.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { VersionAnnouncementsBatchPatchRequestResources } from './VersionAnnouncementsBatchPatchRequestResources';
import {
    VersionAnnouncementsBatchPatchRequestResourcesFromJSON,
    VersionAnnouncementsBatchPatchRequestResourcesFromJSONTyped,
    VersionAnnouncementsBatchPatchRequestResourcesToJSON,
    VersionAnnouncementsBatchPatchRequestResourcesToJSONTyped,
} from './VersionAnnouncementsBatchPatchRequestResources';

/**
 * 
 * @export
 * @interface VersionAnnouncementsBatchPatchRequest
 */
export interface VersionAnnouncementsBatchPatchRequest {
    /**
     * 
     * @type {VersionAnnouncementsBatchPatchRequestResources}
     * @memberof VersionAnnouncementsBatchPatchRequest
     */
    resources?: VersionAnnouncementsBatchPatchRequestResources;
}

/**
 * Check if a given object implements the VersionAnnouncementsBatchPatchRequest interface.
 */
export function instanceOfVersionAnnouncementsBatchPatchRequest(value: object): value is VersionAnnouncementsBatchPatchRequest {
    return true;
}

export function VersionAnnouncementsBatchPatchRequestFromJSON(json: any): VersionAnnouncementsBatchPatchRequest {
    return VersionAnnouncementsBatchPatchRequestFromJSONTyped(json, false);
}

export function VersionAnnouncementsBatchPatchRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): VersionAnnouncementsBatchPatchRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'resources': json['resources'] == null ? undefined : VersionAnnouncementsBatchPatchRequestResourcesFromJSON(json['resources']),
    };
}

export function VersionAnnouncementsBatchPatchRequestToJSON(json: any): VersionAnnouncementsBatchPatchRequest {
    return VersionAnnouncementsBatchPatchRequestToJSONTyped(json, false);
}

export function VersionAnnouncementsBatchPatchRequestToJSONTyped(value?: VersionAnnouncementsBatchPatchRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'resources': VersionAnnouncementsBatchPatchRequestResourcesToJSON(value['resources']),
    };
}

