/* tslint:disable */
/* eslint-disable */
/**
 * PERSCOM Personnel Management System API
 * The PERSCOM API describes how to interact and manipulate your PERSCOM data available at https://perscom.io. The API provides a powerful interface to allow for third-party collaboration and integration with your PERSCOM Dashboard.
 *
 * The version of the OpenAPI document: v2
 * Contact: support@deschutesdesigngroup.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CategoryResource } from './CategoryResource';
import {
    CategoryResourceFromJSON,
    CategoryResourceFromJSONTyped,
    CategoryResourceToJSON,
    CategoryResourceToJSONTyped,
} from './CategoryResource';

/**
 * 
 * @export
 * @interface VersionCategoriesBatchPost200Response
 */
export interface VersionCategoriesBatchPost200Response {
    /**
     * 
     * @type {Array<CategoryResource>}
     * @memberof VersionCategoriesBatchPost200Response
     */
    data?: Array<CategoryResource>;
}

/**
 * Check if a given object implements the VersionCategoriesBatchPost200Response interface.
 */
export function instanceOfVersionCategoriesBatchPost200Response(value: object): value is VersionCategoriesBatchPost200Response {
    return true;
}

export function VersionCategoriesBatchPost200ResponseFromJSON(json: any): VersionCategoriesBatchPost200Response {
    return VersionCategoriesBatchPost200ResponseFromJSONTyped(json, false);
}

export function VersionCategoriesBatchPost200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): VersionCategoriesBatchPost200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'] == null ? undefined : ((json['data'] as Array<any>).map(CategoryResourceFromJSON)),
    };
}

export function VersionCategoriesBatchPost200ResponseToJSON(json: any): VersionCategoriesBatchPost200Response {
    return VersionCategoriesBatchPost200ResponseToJSONTyped(json, false);
}

export function VersionCategoriesBatchPost200ResponseToJSONTyped(value?: VersionCategoriesBatchPost200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': value['data'] == null ? undefined : ((value['data'] as Array<any>).map(CategoryResourceToJSON)),
    };
}

