name: Publish Package

on:
  push:
    paths:
      - 'typescript/**'
      - '.github/workflows/**'
  pull_request:
    paths:
      - 'typescript/**'
      - '.github/workflows/**'

jobs:
  publish:
    name: Publish Package
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: 'https://registry.npmjs.org'

      - name: Install Dependencies
        working-directory: './typescript'
        run: npm ci

      - name: Publish Package
        working-directory: './typescript'
        run: npm publish --provenance --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}